const ELIXIRS: Elixir[] = [
  { name: '강맹', type: '질서', part: '투구' },
  { name: '달인', type: '질서', part: '투구' },
  { name: '선각자', type: '질서', part: '투구' },
  { name: '선봉대', type: '질서', part: '투구' },
  { name: '신념', type: '질서', part: '투구' },
  { name: '진군', type: '질서', part: '투구' },
  { name: '칼날 방패', type: '질서', part: '투구' },
  { name: '행운', type: '질서', part: '투구' },
  { name: '회심', type: '질서', part: '투구' },

  { name: '각성기 피해', part: '어깨' },
  { name: '보스 피해', part: '어깨' },
  { name: '보호막 강화', part: '어깨' },
  { name: '회복 강화', part: '어깨' },

  { name: '마법 방어력', part: '상의' },
  { name: '물리 방어력', part: '상의' },
  { name: '받는 피해 감소', part: '상의' },
  { name: '최대 생명력', part: '상의' },

  { name: '아군 강화', part: '하의' },
  { name: '아이덴티티 획득', part: '하의' },
  { name: '추가 피해', part: '하의' },
  { name: '치명타 피해', part: '하의' },

  { name: '강맹', type: '혼돈', part: '장갑' },
  { name: '달인', type: '혼돈', part: '장갑' },
  { name: '선각자', type: '혼돈', part: '장갑' },
  { name: '선봉대', type: '혼돈', part: '장갑' },
  { name: '신념', type: '혼돈', part: '장갑' },
  { name: '진군', type: '혼돈', part: '장갑' },
  { name: '칼날 방패', type: '혼돈', part: '장갑' },
  { name: '행운', type: '혼돈', part: '장갑' },
  { name: '회심', type: '혼돈', part: '장갑' },

  { name: '공격력' },
  { name: '마나' },
  { name: '무기 공격력' },
  { name: '무력화' },
  { name: '물약 중독' },
  { name: '힘/민첩/지능' },
  { name: '방랑자' },
  { name: '생명의 축복' },
  { name: '자원의 축복' },
  { name: '탈출의 달인' },
  { name: '폭발물 달인' },
  { name: '회피의 달인' },
];
